language: node_js
node_js: stable

# Travis CI Caching
cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run build

after_script:
  - npm run deploy

before_script:
  - git config --global user.name "forecho"
  - git config --global user.email "caizhenghai@gmail.com"
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - sed -i "s/http:\/\/3li3.github.io\/react/$REPO_URL/g" package.json

env:
  global:
    - GH_REPO: 3li3/react
    - secure: "Wt0/TE9gEkGf7ihmimq67qm7XGDI7uR0OI2LW+y1+xQrMdijoZ/OcHayTCh+MA1yFzuXqIIY2m2fkEnBqR0c7N/MY9hOzMd3EqgVM++8zLXokneQsfLFG3gPdfnGbJfcEMihAqMl9R5OLWsu5cXM1E6G2MLW2hQBR1ZtXIw3QazuK/FQmrVa2KzStmIo4jypH3TrRtg1pB+Qj0JUWkVt0d9ebSJSqOriZiGyZs7mLf/Ol7bcsuWQBxuz844hmigIPvlctg0wVRZFx38OmGblze8koDmOK/9lBBYEdMqfa2TZPqaLsow/WFoszgamJx3q87fsJgLUa7UOi+HFivxTxxe/eXResMHSZPxExMhikKyNbCGy8sZ2sOJmzdxPm6vDlg3TwKmq2VgZiL54uX17l01XirUTYSRNPP/abhaihg/+AE8ybuQl5i1b4lLVtcgH13gTx/BXCxeK6ORzxFP/jckT5+bodXuY/NIznOqJfUqY69qtFgirTXxE55PAJmKLa9XaK4yGP8Vqcw7apTl3uFlHQH99GcUzNXw1i6zXEIvXIbu5jYkrpPN0u8zTMkFMtcJEX8sDvLBz3VU13yJC8mC9QM3v8OH+2P2q8D1GP0w4uqKNaPUC23obMSDqGMotk4Ntxtoc2xGrVbPJQzP1156LykdfIgMejYFpA7NZzfY="