language: node_js
node_js: stable

# Travis CI Caching
cache:
  directories:
    - node_modules

install:
  - npm instal

script:
  - npm run build

after_script:
  - cd public
  - git init
  - git config user.name "forecho"
  - git config user.email "caizhenghai@gmail.com"
  - git add .
  - git commit -m "Auto deploy from Travis-CI."
  - git push --force --quiet "https://$GH_Token@github.com/$GH_REPO.git" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - GH_REPO: 3li3/react
    - secure: "Wt0/TE9gEkGf7ihmimq67qm7XGDI7uR0OI2LW+y1+xQrMdijoZ/OcHayTCh+MA1yFzuXqIIY2m2fkEnBqR0c7N/MY9hOzMd3EqgVM++8zLXokneQsfLFG3gPdfnGbJfcEMihAqMl9R5OLWsu5cXM1E6G2MLW2hQBR1ZtXIw3QazuK/FQmrVa2KzStmIo4jypH3TrRtg1pB+Qj0JUWkVt0d9ebSJSqOriZiGyZs7mLf/Ol7bcsuWQBxuz844hmigIPvlctg0wVRZFx38OmGblze8koDmOK/9lBBYEdMqfa2TZPqaLsow/WFoszgamJx3q87fsJgLUa7UOi+HFivxTxxe/eXResMHSZPxExMhikKyNbCGy8sZ2sOJmzdxPm6vDlg3TwKmq2VgZiL54uX17l01XirUTYSRNPP/abhaihg/+AE8ybuQl5i1b4lLVtcgH13gTx/BXCxeK6ORzxFP/jckT5+bodXuY/NIznOqJfUqY69qtFgirTXxE55PAJmKLa9XaK4yGP8Vqcw7apTl3uFlHQH99GcUzNXw1i6zXEIvXIbu5jYkrpPN0u8zTMkFMtcJEX8sDvLBz3VU13yJC8mC9QM3v8OH+2P2q8D1GP0w4uqKNaPUC23obMSDqGMotk4Ntxtoc2xGrVbPJQzP1156LykdfIgMejYFpA7NZzfY="